model:
  random_state: 42
  test_size: 0.2
  n_splits: 5

data:
  numeric_features:
    - Age
    - Balance
    - EstimatedSalary
    - NumOfProducts
    - Tenure
  categorical_features:
    - Gender
    - Geography
    - HasCrCard
    - IsActiveMember
  target_column: Churn
  derived_features:
    - balance_per_product
    - tenure_age_ratio
    - activity_score

paths:
  data_dir: data
  models_dir: models
  output_dir: output 