data:
  numeric_features:
    - Age
    - Balance
    - EstimatedSalary
    - NumOfProducts
    - Tenure
    - CreditScore
    - MonthlyCharges
    - TotalCharges
    - NumTransactions

  categorical_features:
    - Gender
    - Geography
    - HasCrCard
    - IsActiveMember

  id_columns:
    - CustomerID

  derived_features:
    - balance_salary_ratio
    - products_per_tenure
    - active_with_credit_card

  encoding:
    one_hot_encode:
      - Geography
      - Gender
    keep_categorical: []
    encoding_reference:
      Geography: ["Mexico", "USA"]
      Gender: ["M"]  # Only M will be encoded, F is the reference category

paths:
  data_dir: data
  output_dir: output
  models_dir: models