model:
  name: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2

features:
  features_to_create:
    - "balance_salary_ratio"
    - "products_per_tenure"
    - "active_with_credit_card"
    - "age_group"
  scaling_method: "standard"
  categorical_encoding: "onehot"

random_state: 42

gradient_boosting:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3

logistic_regression:
  C: 1.0
  max_iter: 100
  penalty: 'l2' 