random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

gradient_boosting:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3

logistic_regression:
  C: 1.0
  max_iter: 100
  penalty: 'l2' 