model:
  name: "random_forest"
  random_state: 42
  param_grids:
    random_forest:
      n_estimators: [100, 200, 300]
      max_depth: [10, 20, 30, null]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      class_weight: ["balanced", null]
    gradient_boosting:
      n_estimators: [100, 200, 300]
      learning_rate: [0.01, 0.1, 0.3]
      max_depth: [3, 4, 5]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]
    logistic_regression:
      C: [0.001, 0.01, 0.1, 1, 10]
      penalty: ["l2"]
      class_weight: ["balanced", null]
      solver: ["lbfgs"]

features:
  features_to_create:
    - "balance_salary_ratio"
    - "products_per_tenure"
    - "active_with_credit_card"
    - "age_group"
  scaling_method: "standard"
  categorical_encoding: "onehot"